import type { Language, SeoPage } from './seoPages'

const he: SeoPage[] = [
  {
    kind: 'service',
    slug: 'api-development',
    title: 'פיתוח API ו Backend לעסקים | CodeCrafter',
    description: 'פיתוח API ו Backend למערכות עסקיות, אתרים, אפליקציות ואינטגרציות, כולל הרשאות, ולידציה, לוגים ותיעוד סביב תהליך עסקי אמיתי.',
    eyebrow: 'API ו Backend',
    h1: 'פיתוח API ו Backend למערכות עסקיות',
    intro: [
      'API הוא שכבת החיבור שמאפשרת לאתר, אפליקציה, CRM, ERP או שירות צד שלישי לעבוד מול אותם נתונים וכללים בצורה מסודרת. Backend מטפל בלוגיקה העסקית, הרשאות, ולידציה, שמירת מידע ותהליכים שאסור להשאיר רק בצד הדפדפן.',
      'הפיתוח מתחיל מהפעולות שהמערכת צריכה לבצע ומהבעלות על הנתונים, ולא מרשימת endpoints שרירותית. כך אפשר לבנות ממשק יציב שאפליקציות וחיבורים נוספים יכולים להסתמך עליו.',
    ],
    sections: [
      { heading: 'מה אפשר לכלול', items: ['REST API או ממשק שרת מתאים למוצר', 'אימות משתמשים והרשאות לפי תפקיד', 'ולידציה וכללי עסק', 'חיבור למסד נתונים', 'Webhooks ואירועים', 'לוגים, טיפול בשגיאות וניסיונות חוזרים', 'תיעוד למפתחים או למערכות מחוברות'] },
      { heading: 'API פנימי לעומת אינטגרציה חיצונית', paragraphs: ['API פנימי משרת את המוצר עצמו או כמה ממשקים של אותו עסק. אינטגרציה חיצונית מחברת לספק אחר ודורשת להתחשב בהרשאות, מגבלות שימוש ושינויים בצד הספק. בשני המקרים מגדירים מקור אמת, מזהים יציבים והתנהגות בכשל.'] },
      { heading: 'אבטחה והרשאות', paragraphs: ['מפתחות וסודות נשמרים בצד שרת, ההרשאות מצומצמות למה שנדרש, וקלט נבדק לפני ביצוע פעולה. פעולות רגישות יכולות לקבל לוג ביקורת, הגבלת קצב או אישור נוסף לפי הסיכון וההיקף.'] },
      { heading: 'מתי API מותאם הגיוני', paragraphs: ['כאשר כמה ממשקים צריכים לעבוד מול אותם נתונים, כאשר מערכת קיימת צריכה להיחשף בצורה מבוקרת, או כאשר לוגיקה עסקית חייבת להיות עקבית בין אתר, אפליקציה ואינטגרציות. אם ספק קיים כבר מספק API מתאים, לעיתים עדיף להשתמש בו ולא לבנות שכבה כפולה.'] },
    ],
    faq: [
      { question: 'האם API הוא אותו דבר כמו אינטגרציה?', answer: 'לא. API הוא ממשק לתקשורת עם מערכת. אינטגרציה היא התהליך שמחבר בין מערכות ומשתמש ב API, Webhook או דרך מורשית אחרת.' },
      { question: 'אפשר לבנות Backend לאפליקציה קיימת?', answer: 'כן, לאחר בדיקת מבנה הנתונים, האימות, הלקוחות הקיימים והדרך שבה צריך לבצע מעבר בלי לשבור שימוש פעיל.' },
      { question: 'אפשר לחבר את ה API לאפליקציית מובייל ול Web App?', answer: 'כן. שכבת Backend אחת יכולה לשרת כמה ממשקים כאשר ההרשאות והחוזה של ה API מתוכננים לכך.' },
    ],
    relatedServices: ['integrations', 'custom-software', 'web-app-development', 'app-development', 'business-portals', 'automation'],
  },
  {
    kind: 'service',
    slug: 'crm-integrations',
    title: 'אינטגרציות CRM וחיבור CRM למערכות | CodeCrafter',
    description: 'חיבור CRM לאתר, טפסים, דוא״ל, יומן, ERP, אוטומציות ומערכות עסקיות דרך API, Webhooks וממשקים מורשים.',
    eyebrow: 'CRM ואינטגרציות',
    h1: 'אינטגרציות CRM וחיבור CRM למערכות העסק',
    intro: [
      'CRM מאבד מערכו כאשר לידים, פגישות, סטטוסים ומסמכים עדיין עוברים ידנית בין כלים. אינטגרציה טובה מגדירה מה נכנס ל CRM, מה יוצא ממנו, מי מקור האמת ומה קורה אם חיבור נכשל.',
      'אפשר לחבר CRM מותאם או מוצר קיים כאשר קיימים API, Webhooks, ייצוא או ממשק מורשה מתאים. היכולת בפועל נבדקת לפני התחייבות.',
    ],
    sections: [
      { heading: 'חיבורים נפוצים', items: ['טפסי אתר ולידים', 'דוא״ל ותיעוד תקשורת', 'יומן ופגישות', 'מערכת ERP או מלאי', 'אוטומציות ומשימות', 'פורטלים ואפליקציות', 'דוחות וכלי BI כאשר קיימת גישה מתאימה'] },
      { heading: 'מניעת כפילויות ומקור אמת', paragraphs: ['מגדירים מזהים, כללי התאמה ועדכון כדי שליד אחד לא יהפוך לכמה רשומות. לכל סוג מידע נקבע מי מקור האמת ומה עושים כאשר שני צדדים שינו מידע במקביל.'] },
      { heading: 'תהליך אמין ולא רק חיבור חד פעמי', paragraphs: ['חיבור עסקי כולל טיפול בכשל, לוגים, ניסיונות חוזרים והתראה כאשר נדרש טיפול ידני. כאשר הספק מגביל API או משנה הרשאה, הכשל צריך להיות גלוי ולא להיעלם בשקט.'] },
      { heading: 'CRM קיים או CRM מותאם', paragraphs: ['אם ה CRM הקיים מתאים לרוב התהליך, אינטגרציה יכולה להיות עדיפה על החלפה. כאשר המגבלות של המוצר עצמו הן הבעיה, אפשר לבדוק CRM מותאם או מעבר הדרגתי.'] },
    ],
    faq: [
      { question: 'אפשר לחבר CRM לאתר?', answer: 'כן כאשר יש גישה מתאימה. אפשר להעביר לידים וטפסים, ולעיתים גם להחזיר סטטוסים או מידע לפי הרשאה.' },
      { question: 'אפשר לחבר CRM ליומן ולמייל?', answer: 'לעיתים כן. הדבר תלוי בספקים, בהרשאות וב API הזמין לחשבון.' },
      { question: 'צריך להחליף CRM כדי להוסיף אוטומציה?', answer: 'לא בהכרח. אם המערכת הקיימת מספקת חיבורים מתאימים, אפשר לעיתים לשמור אותה ולבנות סביב התהליך הקיים.' },
    ],
    relatedServices: ['crm-development', 'integrations', 'automation', 'api-development', 'erp-development', 'business-portals'],
  },
  {
    kind: 'service',
    slug: 'crm-migration',
    title: 'מיגרציה והעברת נתונים ל CRM | CodeCrafter',
    description: 'מיגרציית CRM והעברת לידים, לקוחות, אנשי קשר, משימות ונתונים ממערכת ישנה או קבצים למבנה CRM חדש בצורה מבוקרת.',
    eyebrow: 'CRM ומיגרציה',
    h1: 'מיגרציה והעברת נתונים ל CRM',
    intro: [
      'מעבר CRM הוא בעיקר פרויקט נתונים ותהליך, לא רק העתקת קובץ. לפני מעבר צריך להבין אילו שדות באמת בשימוש, איך מזהים כפילויות, מה חייב להישמר כהיסטוריה ומה אפשר להשאיר בארכיון.',
      'המטרה היא להגיע למערכת חדשה עם מבנה נקי ומובן, בלי להפוך בעיות ישנות לחלק קבוע מהמערכת החדשה.',
    ],
    sections: [
      { heading: 'מה ממפים לפני מעבר', items: ['לקוחות ואנשי קשר', 'לידים והזדמנויות', 'סטטוסים ושלבים', 'משימות והקצאות', 'הערות והיסטוריה', 'מסמכים וקישורים', 'שדות מותאמים ומזהים חיצוניים'] },
      { heading: 'ניקוי נתונים וכפילויות', paragraphs: ['בודקים פורמטים, ערכים חסרים, מזהים, טלפונים, אימיילים ורשומות כפולות. כללי האיחוד נקבעים מראש כדי לא למחוק מידע חשוב או ליצור קשרים שגויים בין רשומות.'] },
      { heading: 'ייבוא ניסיוני לפני מעבר מלא', paragraphs: ['מבצעים דוגמה או סביבת בדיקה, בודקים ספירות ודוגמאות ידניות, ורק לאחר מכן מבצעים מעבר מלא. אם המערכת הישנה ממשיכה לעבוד בזמן ההעברה, מגדירים נקודת חיתוך או סנכרון זמני.'] },
      { heading: 'מה לא תמיד אפשר להעביר', paragraphs: ['היקף המיגרציה תלוי במה שהמערכת הישנה מאפשרת לייצא. היסטוריית מערכת פנימית, קבצים, הרשאות או שדות מסוימים עלולים להיות מוגבלים, ולכן נבדקת הגישה בפועל לפני שמבטיחים שימור מלא.'] },
    ],
    faq: [
      { question: 'אפשר להעביר CRM מאקסל?', answer: 'כן, אם הקבצים מסודרים מספיק למיפוי. בדרך כלל נדרש ניקוי והגדרת קשרים בין הרשומות לפני הייבוא.' },
      { question: 'אפשר לשמור היסטוריה מהמערכת הישנה?', answer: 'לעיתים כן, אך זה תלוי ביכולת הייצוא ובמבנה הנתונים של המערכת הישנה והחדשה.' },
      { question: 'איך מונעים אובדן מידע?', answer: 'שומרים גיבוי, מבצעים ייבוא ניסיוני, משווים ספירות ודוגמאות, ומתכננים נקודת מעבר ברורה לפני ניתוק המערכת הישנה.' },
    ],
    relatedServices: ['crm-development', 'crm-integrations', 'custom-software', 'integrations', 'automation'],
  },
  {
    kind: 'service',
    slug: 'ecommerce-development',
    title: 'פיתוח חנות אונליין ומסחר אלקטרוני | CodeCrafter',
    description: 'פיתוח חנויות אונליין ומערכות ecommerce לעסקים, כולל קטלוג, סל, תשלום, ניהול הזמנות, תוכן, אינטגרציות ותחזוקה לפי הפלטפורמה.',
    eyebrow: 'Ecommerce',
    h1: 'פיתוח חנות אונליין ומערכות מסחר אלקטרוני',
    intro: [
      'חנות אונליין היא יותר מעמודי מוצר. היא מחברת קטלוג, מחירים, מלאי, תשלום, הזמנות, הודעות, אנליטיקה ולעיתים CRM או ERP.',
      'הבחירה בין Shopify, WordPress/WooCommerce, פיתוח מותאם או פתרון אחר נקבעת לפי המוצרים, התפעול, החיבורים והיכולת של הצוות לנהל את החנות אחרי ההשקה.',
    ],
    sections: [
      { heading: 'מה נכלל באפיון חנות', items: ['קטלוג ומבנה קטגוריות', 'וריאציות ומוצרים', 'סל ותהליך רכישה', 'סליקה ואמצעי תשלום לפי ספק מאושר', 'משלוחים או איסוף', 'ניהול הזמנות וסטטוסים', 'אנליטיקה והמרות', 'חיבור למלאי, CRM או ERP לפי צורך'] },
      { heading: 'בחירת פלטפורמה', paragraphs: ['Shopify מתאים לעסקים שרוצים פלטפורמת מסחר מנוהלת. WordPress/WooCommerce יכול להתאים כאשר התוכן והגמישות באתר חשובים. פיתוח מותאם מתאים כאשר התהליך חורג משמעותית ממה שפלטפורמה קיימת מספקת.'] },
      { heading: 'ניהול אחרי ההשקה', paragraphs: ['הצוות צריך לדעת לעדכן מוצרים, מחירים, תוכן והזמנות בלי תלות מיותרת בפיתוח. לכן ניהול החנות, הרשאות והדרכה בסיסית הם חלק מהתכנון, לא תוספת מאוחרת.'] },
      { heading: 'חיבורים ואמינות', paragraphs: ['חיבור לסליקה, משלוחים, מלאי או מערכת אחרת נבדק לפי API והרשאות זמינים. תהליך הזמנה צריך לטפל גם בכשל תשלום, ניסיון חוזר ועדכון חלקי ולא רק במסלול המוצלח.'] },
    ],
    faq: [
      { question: 'איזו פלטפורמה עדיפה לחנות?', answer: 'אין תשובה אחת. בוחרים לפי קטלוג, תפעול, תקציב, חיבורים ויכולת הניהול של העסק.' },
      { question: 'אפשר לחבר חנות למלאי או CRM?', answer: 'כן כאשר קיימים ממשקים מתאימים. לפני התחייבות נבדקים API, Webhooks והרשאות.' },
      { question: 'אפשר לשדרג חנות קיימת במקום לבנות מחדש?', answer: 'במקרים רבים כן. כדאי לבדוק קודם את מבנה החנות, ביצועים, תבנית, תוספים וחיבורים לפני שמחליטים על בנייה מחדש.' },
    ],
    relatedServices: ['websites', 'shopify-development', 'wordpress-development', 'inventory-systems', 'integrations', 'crm-development'],
  },
  {
    kind: 'service',
    slug: 'shopify-development',
    title: 'פיתוח והקמת חנות Shopify לעסק | CodeCrafter',
    description: 'הקמת ופיתוח Shopify לעסקים: מבנה חנות, תבנית, קטלוג, תשלומים, משלוחים, אפליקציות, אינטגרציות ותחזוקה בהתאם לצורך.',
    eyebrow: 'Shopify',
    h1: 'פיתוח והקמת חנות Shopify',
    intro: [
      'Shopify מספקת תשתית מסחר מנוהלת, אך חנות טובה עדיין דורשת מבנה קטלוג, חוויית רכישה, הגדרות תשלום ומשלוח, תוכן וחיבורים שמתאימים לעסק.',
      'העבודה יכולה לכלול הקמה חדשה, שיפור חנות קיימת או חיבור Shopify למערכות נוספות. אפליקציות ותוספים נבחרים לפי צורך ולא כדי להעמיס על החנות.',
    ],
    sections: [
      { heading: 'הקמה ושיפור', items: ['מבנה קטגוריות וקולקציות', 'עמודי מוצר ותוכן', 'התאמת תבנית', 'הגדרות סל וקופה', 'תשלומים ומשלוחים לפי ספקים זמינים', 'אנליטיקה ומדידה', 'אפליקציות והרחבות לפי צורך'] },
      { heading: 'אינטגרציות Shopify', paragraphs: ['אפשר לבדוק חיבור למלאי, CRM, ERP, דוא״ל, אוטומציה או שירותים נוספים דרך Shopify APIs ואפליקציות מורשות. לכל חיבור מגדירים מקור אמת והתנהגות במקרה של כשל.'] },
      { heading: 'ביצועים ותחזוקה', paragraphs: ['תבניות, אפליקציות וסקריפטים יכולים להשפיע על ביצועים. תחזוקה כוללת בדיקת שינויים, אפליקציות, תהליכי רכישה וחיבורים קריטיים בהתאם למסלול שנקבע.'] },
      { heading: 'מתי Shopify פחות מתאים', paragraphs: ['כאשר התהליך העסקי דורש לוגיקה ייחודית מאוד, הרשאות מורכבות או חוויית מוצר שאינה דומה למסחר רגיל, ייתכן שפתרון מותאם או פלטפורמה אחרת יתאימו יותר.'] },
    ],
    faq: [
      { question: 'אפשר לחבר Shopify למערכת מלאי?', answer: 'כן כאשר המערכת והחשבון מספקים API או חיבור מורשה מתאים.' },
      { question: 'אפשר לעבוד על חנות Shopify קיימת?', answer: 'כן. אפשר לבדוק תבנית, אפליקציות, מבנה, ביצועים וחיבורים ולהגדיר שיפור ממוקד.' },
      { question: 'האם כל אפליקציה בחנות היא בתשלום?', answer: 'לא. התמחור והרישוי נקבעים על ידי ספקי האפליקציות ומשתנים בין פתרונות, ולכן נבדקים לפני בחירה.' },
    ],
    relatedServices: ['ecommerce-development', 'websites', 'integrations', 'inventory-systems', 'crm-integrations', 'website-maintenance'],
  },
  {
    kind: 'service',
    slug: 'wordpress-development',
    title: 'פיתוח ובניית אתר WordPress לעסק | CodeCrafter',
    description: 'פיתוח WordPress לעסקים: אתרי תדמית, תוכן, WooCommerce, התאמות, אינטגרציות, ביצועים ותחזוקה לפי הצורך.',
    eyebrow: 'WordPress',
    h1: 'פיתוח ובניית אתר WordPress לעסק',
    intro: [
      'WordPress מתאים לפרויקטים רבים שבהם העסק צריך מערכת ניהול תוכן מוכרת ואקוסיסטם רחב של תוספים. הבחירה בו צריכה להגיע מהתאמה לצורך ולא מהרגל בלבד.',
      'אפשר לבנות אתר חדש, לשפר אתר קיים, לחבר WooCommerce או לבצע התאמות ואינטגרציות תוך שמירה על מספר סביר של תוספים ועל תהליך עדכון ברור.',
    ],
    sections: [
      { heading: 'מה אפשר לבנות', items: ['אתרי תדמית ותוכן', 'עמודי שירות ונחיתה', 'בלוגים ומאגרי תוכן', 'WooCommerce', 'טפסים ואינטגרציות', 'תבניות ורכיבים מותאמים'] },
      { heading: 'תוספים, אבטחה ותחזוקה', paragraphs: ['כל תוסף הוא תלות נוספת. בוחרים תוספים לפי צורך, מקור ותחזוקה פעילה, מעדכנים בסביבה מבוקרת ושומרים גיבוי לפני שינויים משמעותיים.'] },
      { heading: 'ביצועים ונגישות', paragraphs: ['תמונות, תוספים, בוני עמודים וסקריפטים משפיעים על ביצועים. התכנון צריך לשמור על חוויית מובייל טובה, מבנה HTML ברור ונגישות בהתאם להיקף הפרויקט.'] },
      { heading: 'WordPress לעומת פיתוח מותאם', paragraphs: ['WordPress חזק כאשר מבנה האתר ותהליך הניהול מתאימים למערכת. כאשר נדרש מוצר Web מורכב, הרשאות עמוקות או לוגיקה עסקית מיוחדת, מערכת מותאמת יכולה להיות פשוטה יותר לאורך זמן.'] },
    ],
    faq: [
      { question: 'אפשר לשדרג אתר WordPress קיים?', answer: 'כן. מתחילים מבדיקה של גרסאות, תבנית, תוספים, ביצועים וגיבוי לפני שינוי.' },
      { question: 'אפשר לבנות חנות עם WordPress?', answer: 'כן, בדרך כלל באמצעות WooCommerce כאשר הוא מתאים להיקף ולתפעול.' },
      { question: 'WordPress מתאים לכל מערכת?', answer: 'לא. הוא מצוין לניהול תוכן ומסחר במקרים רבים, אבל מערכת עסקית מורכבת עשויה להתאים יותר לפיתוח ייעודי.' },
    ],
    relatedServices: ['websites', 'ecommerce-development', 'website-maintenance', 'integrations', 'cms-development'],
  },
  {
    kind: 'service',
    slug: 'wix-development',
    title: 'בניית ושיפור אתר Wix לעסק | CodeCrafter',
    description: 'בניית ושיפור אתרי Wix לעסקים, כולל מבנה, עיצוב, תוכן, טפסים, חיבורים, SEO טכני בסיסי ותחזוקה בהתאם ליכולות הפלטפורמה.',
    eyebrow: 'Wix',
    h1: 'בניית ושיפור אתר Wix לעסק',
    intro: [
      'Wix יכול להתאים לעסק שרוצה מערכת מנוהלת עם עריכת תוכן ועיצוב במקום אחד. היתרון הוא ניהול פשוט יחסית; המגבלה היא שהפיתוח נשאר בתוך היכולות וה APIs שהפלטפורמה מאפשרת.',
      'אפשר להקים אתר, לסדר מבנה קיים, לשפר מובייל, טפסים וניווט, ולבדוק חיבורים חיצוניים כאשר קיימת תמיכה רשמית.',
    ],
    sections: [
      { heading: 'מה אפשר לשפר', items: ['מבנה עמודים וניווט', 'עיצוב רספונסיבי', 'טפסים ויצירת קשר', 'תוכן ומטא נתונים', 'ביצועים במסגרת הפלטפורמה', 'חיבורים ושירותים נתמכים'] },
      { heading: 'מגבלות פלטפורמה', paragraphs: ['לא כל שינוי שאפשר לבצע בקוד מותאם אפשר לבצע באותה צורה ב Wix. לפני שמתחייבים לפיצר בודקים את ה API, Velo או הממשק הרשמי הזמין בזמן הפרויקט.'] },
      { heading: 'מתי להישאר ב Wix', paragraphs: ['אם הצוות מכיר את המערכת והיא מכסה את רוב הצורך, שיפור ממוקד יכול להיות הגיוני יותר ממעבר מלא. מעבר נשקל כאשר המגבלות עצמן חוסמות תהליך מרכזי.'] },
      { heading: 'מעבר עתידי', paragraphs: ['אם נדרש מעבר לפלטפורמה אחרת, ממפים תוכן, URLs, טפסים, מדידה וקישורים לפני השקה כדי לצמצם שבירות ואובדן מידע.'] },
    ],
    faq: [
      { question: 'אפשר לערוך אתר Wix קיים?', answer: 'כן, בהתאם להרשאות לחשבון ולמבנה האתר.' },
      { question: 'אפשר לחבר Wix ל CRM?', answer: 'לעיתים כן, אם קיימת אינטגרציה או API מתאים. היכולת נבדקת לפי המערכת והחשבון.' },
      { question: 'צריך לעבור מ Wix כדי לשפר SEO?', answer: 'לא בהכרח. קודם בודקים מבנה, תוכן, אינדוקס, מהירות ומגבלות אמיתיות לפני החלטת מעבר.' },
    ],
    relatedServices: ['websites', 'integrations', 'crm-integrations', 'website-maintenance'],
  },
  {
    kind: 'service',
    slug: 'website-maintenance',
    title: 'תחזוקת אתרים ומערכות לעסקים | CodeCrafter',
    description: 'תחזוקת אתרים ומערכות לעסקים: עדכונים, תיקונים, גיבויים, בדיקות, שיפור ביצועים ומעקב אחר חיבורים בהתאם לטכנולוגיה ולהיקף שנקבע.',
    eyebrow: 'תחזוקה ותמיכה',
    h1: 'תחזוקת אתרים ומערכות לעסקים',
    intro: [
      'אתר או מערכת ממשיכים להשתנות אחרי ההשקה: דפדפנים מתעדכנים, APIs משתנים, תוספים מקבלים גרסאות חדשות ותוכן מתווסף. תחזוקה נועדה לשמור על המוצר עובד ולבצע שינויים בצורה מבוקרת.',
      'היקף התחזוקה תלוי בטכנולוגיה ובחשיבות המערכת. אתר תוכן פשוט דורש מסגרת אחרת ממערכת עסקית עם משתמשים, הרשאות ואינטגרציות.',
    ],
    sections: [
      { heading: 'מה תחזוקה יכולה לכלול', items: ['תיקוני תקלות', 'עדכוני תוכנה ותלויות', 'גיבויים ובדיקת שחזור לפי היקף', 'בדיקת טפסים ותהליכים קריטיים', 'שיפור ביצועים נקודתי', 'שינויים קטנים בתוכן או UI', 'מעקב אחר אינטגרציות ושגיאות'] },
      { heading: 'תחזוקה מונעת', paragraphs: ['עדיף לזהות תלות מיושנת, תוסף בעייתי או API שמשתנה לפני שהם שוברים תהליך עסקי. לכן מסלול קבוע יכול לכלול בדיקות תקופתיות ולא רק תגובה אחרי תקלה.'] },
      { heading: 'גיבוי לפני שינוי משמעותי', paragraphs: ['לפני עדכון משמעותי שומרים נקודת חזרה מתאימה לטכנולוגיה. במערכת עם נתונים חיים נדרש תכנון זהיר יותר מאשר באתר סטטי, במיוחד כאשר יש מסד נתונים או קבצים שממשיכים להשתנות.'] },
      { heading: 'מתי תחזוקה הופכת לפרויקט', paragraphs: ['שדרוג גרסה גדולה, החלפת תשתית, מעבר פלטפורמה או שינוי עמוק בתהליך אינם בהכרח משימת תחזוקה קטנה. במקרה כזה מגדירים פרויקט נפרד עם בדיקות והיקף ברור.'] },
    ],
    faq: [
      { question: 'אפשר לתחזק אתר שלא CodeCrafter בנתה?', answer: 'לעיתים כן. קודם בודקים את הקוד, הגישה, התלויות והמצב הקיים לפני שמתחייבים למסלול.' },
      { question: 'תחזוקה כוללת אחסון?', answer: 'לא בהכרח. אחסון ותחזוקה הם שירותים נפרדים אלא אם הוגדר אחרת בהצעה.' },
      { question: 'יש מסלולי תחזוקה קבועים?', answer: 'כן. המחירון המרכזי מציג את מסלולי התחזוקה והמחירים הנוכחיים.' },
    ],
    relatedServices: ['websites', 'wordpress-development', 'shopify-development', 'custom-software', 'integrations'],
  },
  {
    kind: 'service',
    slug: 'landing-page-development',
    title: 'בניית דף נחיתה לעסק ולקמפיין | CodeCrafter',
    description: 'בניית דפי נחיתה לעסקים ולקמפיינים עם מסר ברור, מבנה רספונסיבי, טופס או WhatsApp, מדידה, ביצועים ותשתית SEO בסיסית לפי הצורך.',
    eyebrow: 'דפי נחיתה',
    h1: 'בניית דף נחיתה לעסק ולקמפיין',
    intro: [
      'דף נחיתה נועד למסלול אחד ברור: להסביר הצעה, לענות על השאלות המרכזיות ולהוביל לפעולה בלי ניווט מיותר. הוא מתאים לקמפיין, שירות ממוקד, השקה או צורך עסקי שבו אתר מלא אינו נדרש.',
      'הדף צריך לעבוד היטב במובייל, לטעון מהר, למדוד את הפעולות החשובות ולשלוח את הפנייה למקום שבו העסק באמת מטפל בה.',
    ],
    sections: [
      { heading: 'מבנה שעוזר להבין מהר', items: ['כותרת והצעת ערך', 'הסבר השירות או המוצר', 'הוכחות או מידע תומך כאשר קיים', 'שאלות נפוצות', 'קריאה לפעולה', 'טופס, טלפון או WhatsApp', 'מדידה ואנליטיקה לפי הצורך'] },
      { heading: 'חיבור ל CRM ולאוטומציה', paragraphs: ['אפשר להעביר פנייה ל CRM או לתהליך המשך כאשר קיים API או חיבור מורשה מתאים. חשוב לשמור גם מצב כשל כדי שפנייה לא תיעלם אם שירות צד שלישי לא זמין.'] },
      { heading: 'דף נחיתה לעומת אתר מלא', paragraphs: ['דף נחיתה מתאים להצעה אחת או קמפיין ממוקד. כאשר העסק צריך להציג כמה שירותים, תוכן מתמשך, אמון רחב וחיפוש אורגני סביב נושאים שונים, אתר רב עמודים בדרך כלל מתאים יותר.'] },
      { heading: 'מדידה לפני שיפור', paragraphs: ['אירועים כמו שליחת טופס, לחיצה על WhatsApp או טלפון יכולים להימדד. שיפור מבוסס על נתונים אמיתיים ולא על שינוי עיצוב אקראי בלבד.'] },
    ],
    faq: [
      { question: 'כמה עולה דף נחיתה?', answer: 'המחירון המרכזי מציג את המחיר המנחה הנוכחי לדף נחיתה.' },
      { question: 'אפשר לחבר דף נחיתה ל WhatsApp?', answer: 'כן. אפשר להוסיף פעולה ישירה ל WhatsApp וגם למדוד לחיצות בהתאם לכלי המדידה שנבחר.' },
      { question: 'דף נחיתה יכול להופיע בגוגל?', answer: 'כן אם הוא ציבורי ואינדקסבילי, אך אין הבטחה למיקום מסוים. לקידום מגוון נושאים אתר עם ארכיטקטורת תוכן רחבה יכול להתאים יותר.' },
    ],
    relatedServices: ['websites', 'crm-integrations', 'automation', 'integrations'],
  },
]

const en: SeoPage[] = [
  {
    kind: 'service',
    slug: 'api-development',
    title: 'API and Backend Development for Business | CodeCrafter',
    description: 'API and backend development for business systems, websites, apps, and integrations, including permissions, validation, logging, and reliable business logic.',
    eyebrow: 'API and backend',
    h1: 'API and backend development for business systems',
    intro: [
      'An API is the connection layer that lets a website, app, CRM, ERP, or third party service work with the same data and rules in a controlled way. The backend handles business logic, permissions, validation, persistence, and processes that should not live only in the browser.',
      'Development starts with the actions the system must support and ownership of the data rather than an arbitrary endpoint list. That creates a stable interface that additional applications and integrations can rely on.',
    ],
    sections: [
      { heading: 'What can be included', items: ['REST API or another suitable server interface', 'Authentication and role based permissions', 'Validation and business rules', 'Database access', 'Webhooks and events', 'Logs, error handling, and bounded retries', 'Developer or integration documentation'] },
      { heading: 'Internal API versus external integration', paragraphs: ['An internal API serves the product or several interfaces owned by the same business. An external integration connects to another provider and must respect its permissions, quotas, and changes. Both need a clear source of truth, stable identifiers, and defined failure behavior.'] },
      { heading: 'Security and permissions', paragraphs: ['Keys and secrets stay server side, permissions are limited to what the workflow needs, and input is validated before material actions run. Sensitive operations can add audit logging, rate limits, or additional approval where the scope requires it.'] },
      { heading: 'When a custom API makes sense', paragraphs: ['A custom API is useful when several interfaces need the same data, when an existing system needs controlled access, or when business rules must stay consistent across a website, app, and integrations. If an existing provider already exposes the right API, using it may be better than building a duplicate layer.'] },
    ],
    faq: [
      { question: 'Is an API the same as an integration?', answer: 'No. An API is an interface for communicating with a system. An integration is the workflow that connects systems using an API, webhook, or another authorized method.' },
      { question: 'Can you build a backend for an existing app?', answer: 'Yes, after reviewing the existing data model, authentication, clients, and a migration path that does not break active use.' },
      { question: 'Can one API serve both a mobile app and a web app?', answer: 'Yes. One backend can serve several interfaces when the API contract and permission model are designed for that use.' },
    ],
    relatedServices: ['integrations', 'custom-software', 'web-app-development', 'app-development', 'business-portals', 'automation'],
  },
  {
    kind: 'service',
    slug: 'crm-integrations',
    title: 'CRM Integrations and CRM System Connections | CodeCrafter',
    description: 'Connect CRM to websites, forms, email, calendars, ERP, automation, and business systems through APIs, webhooks, and other authorized interfaces.',
    eyebrow: 'CRM integrations',
    h1: 'CRM integrations and connections to business systems',
    intro: [
      'A CRM loses value when leads, meetings, statuses, and documents still move manually between tools. A useful integration defines what enters the CRM, what leaves it, the source of truth, and what happens when a connection fails.',
      'A custom CRM or an existing product can be connected when suitable APIs, webhooks, exports, or another authorized interface are available. Capabilities are checked before commitment.',
    ],
    sections: [
      { heading: 'Common connections', items: ['Website forms and leads', 'Email and communication records', 'Calendars and meetings', 'ERP or inventory systems', 'Automation and tasks', 'Portals and apps', 'Reporting or BI tools when access is available'] },
      { heading: 'Deduplication and source of truth', paragraphs: ['Stable identifiers and matching rules help keep one lead from becoming several records. Each data type needs an authoritative source and a conflict rule when both sides change at the same time.'] },
      { heading: 'Reliable workflow, not a one off connection', paragraphs: ['Business connections need failure handling, logs, bounded retries, and alerts when manual action is needed. If a provider changes an API or permission, the failure should be visible rather than silently dropping work.'] },
      { heading: 'Existing CRM or custom CRM', paragraphs: ['If the current CRM fits most of the process, integration may be more sensible than replacement. When the product limitations are the problem, a custom CRM or phased migration can be evaluated.'] },
    ],
    faq: [
      { question: 'Can a CRM connect to a website?', answer: 'Yes when suitable access exists. Leads and forms can be sent in, and some systems can return statuses or data according to permission.' },
      { question: 'Can CRM connect to calendar and email?', answer: 'Often yes, depending on the providers, account permissions, and available API.' },
      { question: 'Do we need to replace the CRM to add automation?', answer: 'Not necessarily. If the current system exposes suitable interfaces, it can often stay in place while automation is built around the existing workflow.' },
    ],
    relatedServices: ['crm-development', 'integrations', 'automation', 'api-development', 'erp-development', 'business-portals'],
  },
  {
    kind: 'service',
    slug: 'crm-migration',
    title: 'CRM Migration and Data Transfer | CodeCrafter',
    description: 'CRM migration for leads, customers, contacts, tasks, and business data from an old system or files into a new CRM structure with controlled validation.',
    eyebrow: 'CRM migration',
    h1: 'CRM migration and data transfer',
    intro: [
      'A CRM move is primarily a data and workflow project, not just a file copy. Before migration, fields, duplicates, required history, and data that can remain archived need to be understood.',
      'The goal is to enter the new system with a clean, understandable structure instead of making old data problems permanent.',
    ],
    sections: [
      { heading: 'What is mapped before migration', items: ['Customers and contacts', 'Leads and opportunities', 'Statuses and stages', 'Tasks and assignments', 'Notes and history', 'Documents and links', 'Custom fields and external identifiers'] },
      { heading: 'Cleaning data and duplicates', paragraphs: ['Formats, missing values, identifiers, phone numbers, emails, and duplicates are checked. Merge rules are agreed in advance so important information is not removed and incorrect relationships are not created.'] },
      { heading: 'Trial import before the full move', paragraphs: ['A sample or test environment is imported first, counts and representative records are checked, and only then is the full transfer performed. If the old CRM stays active during migration, a cutover point or temporary synchronization needs to be defined.'] },
      { heading: 'What may not be portable', paragraphs: ['Migration depends on what the old product can export. Internal audit history, files, permissions, or some custom data may be limited, so actual access is reviewed before complete preservation is promised.'] },
    ],
    faq: [
      { question: 'Can CRM data be migrated from Excel?', answer: 'Yes when the files are structured enough to map. Cleaning and relationship mapping are often required before import.' },
      { question: 'Can old system history be preserved?', answer: 'Sometimes. It depends on the export capability and the data model of both the old and new systems.' },
      { question: 'How is data loss reduced?', answer: 'Keep a backup, run a trial import, compare counts and sample records, and define a clear cutover before the old system is retired.' },
    ],
    relatedServices: ['crm-development', 'crm-integrations', 'custom-software', 'integrations', 'automation'],
  },
  {
    kind: 'service',
    slug: 'ecommerce-development',
    title: 'Ecommerce and Online Store Development | CodeCrafter',
    description: 'Online store and ecommerce development for product catalogs, checkout, payments, order management, content, integrations, and ongoing maintenance.',
    eyebrow: 'Ecommerce',
    h1: 'Ecommerce and online store development',
    intro: [
      'An online store is more than product pages. It connects catalog data, pricing, inventory, payment, orders, notifications, analytics, and sometimes CRM or ERP.',
      'The choice between Shopify, WordPress/WooCommerce, custom development, or another platform should follow the products, operations, integrations, and the team that will manage the store after launch.',
    ],
    sections: [
      { heading: 'What store discovery covers', items: ['Catalog and category structure', 'Products and variants', 'Cart and checkout', 'Payments through an approved provider', 'Shipping or collection', 'Order management and statuses', 'Analytics and conversion tracking', 'Inventory, CRM, or ERP connections where needed'] },
      { heading: 'Choosing a platform', paragraphs: ['Shopify suits businesses that want a managed commerce platform. WordPress/WooCommerce can fit when content and website flexibility are central. Custom development is more appropriate when the workflow materially exceeds what an existing platform provides.'] },
      { heading: 'Management after launch', paragraphs: ['The team should be able to manage products, prices, content, and orders without unnecessary developer dependency. Admin workflow, permissions, and basic handoff are therefore part of planning rather than an afterthought.'] },
      { heading: 'Connections and reliability', paragraphs: ['Payment, shipping, inventory, and other connections are checked against available APIs and permissions. Order flow must account for failed payments, retries, and partial updates rather than only the success path.'] },
    ],
    faq: [
      { question: 'Which ecommerce platform is best?', answer: 'There is no universal answer. Choose based on catalog, operations, budget, integrations, and how the business needs to manage the store.' },
      { question: 'Can a store connect to inventory or CRM?', answer: 'Yes when suitable interfaces are available. APIs, webhooks, and permissions are checked before commitment.' },
      { question: 'Can an existing store be improved instead of rebuilt?', answer: 'Often yes. Review structure, performance, theme, extensions, and integrations before deciding that a rebuild is necessary.' },
    ],
    relatedServices: ['websites', 'shopify-development', 'wordpress-development', 'inventory-systems', 'integrations', 'crm-development'],
  },
  {
    kind: 'service',
    slug: 'shopify-development',
    title: 'Shopify Store Development for Business | CodeCrafter',
    description: 'Shopify store setup and development for catalog structure, themes, checkout, payments, shipping, apps, integrations, and maintenance.',
    eyebrow: 'Shopify',
    h1: 'Shopify store development',
    intro: [
      'Shopify provides managed commerce infrastructure, but a useful store still needs catalog structure, purchase flow, payment and shipping configuration, content, and integrations that fit the business.',
      'Work can include a new store, improvements to an existing store, or connecting Shopify to other systems. Apps and extensions are selected for real requirements rather than added by default.',
    ],
    sections: [
      { heading: 'Setup and improvement', items: ['Collections and category structure', 'Product and content pages', 'Theme adaptation', 'Cart and checkout settings', 'Payments and shipping through available providers', 'Analytics and measurement', 'Apps and extensions where useful'] },
      { heading: 'Shopify integrations', paragraphs: ['Inventory, CRM, ERP, email, automation, and other connections can be evaluated through Shopify APIs and authorized apps. Each connection needs a source of truth and defined behavior when it fails.'] },
      { heading: 'Performance and maintenance', paragraphs: ['Themes, apps, and scripts affect performance. Maintenance can cover changes, apps, purchase flows, and critical integrations according to the agreed plan.'] },
      { heading: 'When Shopify may not fit', paragraphs: ['If the business process needs highly unusual logic, complex permissions, or a product experience far from standard commerce, a custom solution or another platform may be more appropriate.'] },
    ],
    faq: [
      { question: 'Can Shopify connect to an inventory system?', answer: 'Yes when the systems and account expose an appropriate API or authorized connector.' },
      { question: 'Can you work on an existing Shopify store?', answer: 'Yes. Theme, apps, structure, performance, and integrations can be reviewed for focused improvements.' },
      { question: 'Are all Shopify apps paid?', answer: 'No. Pricing and licensing are controlled by app providers and vary, so they should be checked before selection.' },
    ],
    relatedServices: ['ecommerce-development', 'websites', 'integrations', 'inventory-systems', 'crm-integrations', 'website-maintenance'],
  },
  {
    kind: 'service',
    slug: 'wordpress-development',
    title: 'WordPress Website Development for Business | CodeCrafter',
    description: 'WordPress development for business websites, content, WooCommerce, customizations, integrations, performance, and maintenance.',
    eyebrow: 'WordPress',
    h1: 'WordPress website development for business',
    intro: [
      'WordPress fits many projects that need a familiar content management system and a broad extension ecosystem. It should be chosen because it fits the requirement, not only because it is common.',
      'A project can include a new site, improvements to an existing installation, WooCommerce, custom components, or integrations while keeping dependencies and update procedures under control.',
    ],
    sections: [
      { heading: 'What can be built', items: ['Business and content websites', 'Service and landing pages', 'Blogs and content libraries', 'WooCommerce', 'Forms and integrations', 'Custom themes and components'] },
      { heading: 'Plugins, security, and maintenance', paragraphs: ['Every plugin is another dependency. Plugins should be selected for a real need and an active maintenance history, updated carefully, and backed up before material changes.'] },
      { heading: 'Performance and accessibility', paragraphs: ['Images, plugins, page builders, and scripts can affect performance. Planning should preserve a useful mobile experience, clear HTML structure, and accessibility appropriate to the project scope.'] },
      { heading: 'WordPress versus custom development', paragraphs: ['WordPress is strong when site structure and content workflow fit the platform. A complex web product with deep permissions or unusual business logic can be simpler to maintain as a dedicated application.'] },
    ],
    faq: [
      { question: 'Can an existing WordPress site be upgraded?', answer: 'Yes. Versions, theme, plugins, performance, and backups should be reviewed before changes.' },
      { question: 'Can WordPress be used for ecommerce?', answer: 'Yes, commonly through WooCommerce when it fits the operational scope.' },
      { question: 'Is WordPress suitable for every system?', answer: 'No. It is strong for content and many commerce cases, while complex operational software may be better as a dedicated system.' },
    ],
    relatedServices: ['websites', 'ecommerce-development', 'website-maintenance', 'integrations', 'cms-development'],
  },
  {
    kind: 'service',
    slug: 'wix-development',
    title: 'Wix Website Development and Improvement | CodeCrafter',
    description: 'Wix website development and improvement for structure, responsive design, content, forms, integrations, basic technical SEO, and maintenance within platform capabilities.',
    eyebrow: 'Wix',
    h1: 'Wix website development and improvement',
    intro: [
      'Wix can fit a business that wants a managed platform with content and design editing in one place. The advantage is relatively simple management; the limitation is that development stays within the capabilities and APIs the platform exposes.',
      'A project can set up a site, reorganize an existing one, improve mobile behavior, forms, and navigation, and evaluate external connections when official support exists.',
    ],
    sections: [
      { heading: 'What can be improved', items: ['Page structure and navigation', 'Responsive design', 'Forms and contact flows', 'Content and metadata', 'Performance within platform limits', 'Supported integrations and services'] },
      { heading: 'Platform constraints', paragraphs: ['Not every change possible in custom code can be implemented the same way in Wix. Before a feature is promised, the current API, Velo capability, or official integration is checked.'] },
      { heading: 'When staying on Wix makes sense', paragraphs: ['If the team knows the platform and it covers most requirements, focused improvement may be more sensible than a full migration. Migration is considered when platform constraints block a central workflow.'] },
      { heading: 'Future migration', paragraphs: ['If the site moves later, content, URLs, forms, measurement, and links should be mapped before launch to reduce broken paths and data loss.'] },
    ],
    faq: [
      { question: 'Can you edit an existing Wix site?', answer: 'Yes, subject to account access and the existing site structure.' },
      { question: 'Can Wix connect to a CRM?', answer: 'Sometimes, when a suitable integration or API exists. Capability depends on the system and account.' },
      { question: 'Do we need to leave Wix to improve SEO?', answer: 'Not necessarily. Structure, content, indexing, speed, and actual platform limitations should be reviewed before deciding to migrate.' },
    ],
    relatedServices: ['websites', 'integrations', 'crm-integrations', 'website-maintenance'],
  },
  {
    kind: 'service',
    slug: 'website-maintenance',
    title: 'Website and Business System Maintenance | CodeCrafter',
    description: 'Website and system maintenance for updates, fixes, backups, testing, performance work, and integration monitoring according to the technology and agreed scope.',
    eyebrow: 'Maintenance and support',
    h1: 'Website and business system maintenance',
    intro: [
      'A website or application keeps changing after launch: browsers update, APIs change, extensions release new versions, and content evolves. Maintenance keeps the product working and makes changes in a controlled way.',
      'The maintenance scope depends on the technology and criticality of the system. A simple content site needs a different service model from an operational application with users, permissions, and integrations.',
    ],
    sections: [
      { heading: 'Maintenance can include', items: ['Bug fixes', 'Software and dependency updates', 'Backups and restore checks where in scope', 'Checks of forms and critical flows', 'Focused performance improvements', 'Small content or UI changes', 'Monitoring integration failures'] },
      { heading: 'Preventive maintenance', paragraphs: ['It is better to identify an outdated dependency, risky extension, or changing API before it breaks an important process. A recurring plan can therefore include periodic checks rather than only reacting after a failure.'] },
      { heading: 'Backup before material changes', paragraphs: ['A suitable rollback point is created before significant updates. Live applications with changing data need more careful planning than static sites, especially when databases or user files are involved.'] },
      { heading: 'When maintenance becomes a project', paragraphs: ['A major version upgrade, infrastructure replacement, platform migration, or deep workflow change is not always a small maintenance task. It may need a separate project scope with testing and rollout planning.'] },
    ],
    faq: [
      { question: 'Can you maintain a site CodeCrafter did not build?', answer: 'Sometimes. Code, access, dependencies, and the current condition should be reviewed before a maintenance commitment.' },
      { question: 'Does maintenance include hosting?', answer: 'Not automatically. Hosting and maintenance are separate services unless an agreement states otherwise.' },
      { question: 'Are recurring maintenance plans available?', answer: 'Yes. The central pricing page lists the current maintenance plans and published prices.' },
    ],
    relatedServices: ['websites', 'wordpress-development', 'shopify-development', 'custom-software', 'integrations'],
  },
  {
    kind: 'service',
    slug: 'landing-page-development',
    title: 'Landing Page Development for Business and Campaigns | CodeCrafter',
    description: 'Landing page development for businesses and campaigns with clear messaging, responsive layout, forms or WhatsApp, measurement, performance, and basic technical SEO.',
    eyebrow: 'Landing pages',
    h1: 'Landing page development for business and campaigns',
    intro: [
      'A landing page should support one clear journey: explain the offer, answer the main questions, and lead to an action without unnecessary navigation. It fits a campaign, focused service, launch, or business need that does not require a full website.',
      'The page should work well on mobile, load quickly, measure important actions, and send enquiries into the place where the business actually handles them.',
    ],
    sections: [
      { heading: 'A structure visitors can understand quickly', items: ['Headline and value proposition', 'Service or product explanation', 'Proof or supporting information when available', 'Frequently asked questions', 'Call to action', 'Form, phone, or WhatsApp', 'Analytics and measurement where needed'] },
      { heading: 'CRM and automation connections', paragraphs: ['An enquiry can be passed to CRM or a follow-up workflow when a suitable API or authorized connection exists. Failure handling also matters so a lead does not disappear when a third party service is unavailable.'] },
      { heading: 'Landing page versus full website', paragraphs: ['A landing page fits one offer or focused campaign. When a business needs several services, ongoing content, broader trust, and organic search across multiple topics, a multi-page website is usually the stronger structure.'] },
      { heading: 'Measure before changing', paragraphs: ['Events such as form submissions, WhatsApp clicks, or calls can be measured. Improvements should follow real data rather than arbitrary design changes alone.'] },
    ],
    faq: [
      { question: 'How much does a landing page cost?', answer: 'The central pricing page lists the current published starting guidance for a landing page.' },
      { question: 'Can a landing page connect to WhatsApp?', answer: 'Yes. It can include a direct WhatsApp action and clicks can be measured with the selected analytics setup.' },
      { question: 'Can a landing page rank in Google?', answer: 'It can be indexable, but no specific ranking can be guaranteed. A broader site architecture may be more suitable when the business needs to target several topics.' },
    ],
    relatedServices: ['websites', 'crm-integrations', 'automation', 'integrations'],
  },
]

export const commercialPagesByLanguage: Record<Language, SeoPage[]> = { he, en }
