export type Language = 'he' | 'en'

export const serviceSlugs = [
  'websites',
  'crm-development',
  'app-development',
  'automation',
  'custom-software',
  'cms-development',
  'integrations',
  'business-bots',
  'erp-development',
  'inventory-systems',
  'business-portals',
  'web-app-development',
  'api-development',
  'crm-integrations',
  'crm-migration',
  'ecommerce-development',
  'shopify-development',
  'wordpress-development',
  'wix-development',
  'website-maintenance',
  'landing-page-development',
] as const

export const serviceLabels: Record<Language, Record<string, string>> = {
  he: {
    websites: 'בניית אתרים לעסקים',
    'custom-software': 'פיתוח מערכות לעסקים',
    automation: 'אוטומציה לעסקים',
    'crm-development': 'פיתוח מערכת CRM בהתאמה אישית',
    'app-development': 'פיתוח אפליקציות מובייל לעסקים',
    'cms-development': 'פיתוח מערכת CMS בהתאמה לעסק',
    integrations: 'אינטגרציות בין מערכות לעסקים',
    'business-bots': 'פיתוח בוטים לעסקים',
    'erp-development': 'פיתוח מערכת ERP לעסק',
    'inventory-systems': 'מערכות מלאי ומחסנים',
    'business-portals': 'פורטלים עסקיים',
    'web-app-development': 'פיתוח Web Apps',
    'api-development': 'פיתוח API ו Backend',
    'crm-integrations': 'אינטגרציות CRM',
    'crm-migration': 'מיגרציית CRM',
    'ecommerce-development': 'פיתוח חנות אונליין ו Ecommerce',
    'shopify-development': 'פיתוח Shopify',
    'wordpress-development': 'פיתוח WordPress',
    'wix-development': 'פיתוח Wix',
    'website-maintenance': 'תחזוקת אתרים ומערכות',
    'landing-page-development': 'בניית דפי נחיתה',
  },
  en: {
    websites: 'Business websites',
    'custom-software': 'Custom business software',
    automation: 'Business automation',
    'crm-development': 'Custom CRM development',
    'app-development': 'Mobile app development',
    'cms-development': 'Custom CMS development',
    integrations: 'Business systems integration',
    'business-bots': 'Business bot development',
    'erp-development': 'Custom ERP development',
    'inventory-systems': 'Inventory and warehouse systems',
    'business-portals': 'Business portals',
    'web-app-development': 'Web app development',
    'api-development': 'API and backend development',
    'crm-integrations': 'CRM integrations',
    'crm-migration': 'CRM migration',
    'ecommerce-development': 'Ecommerce development',
    'shopify-development': 'Shopify development',
    'wordpress-development': 'WordPress development',
    'wix-development': 'Wix development',
    'website-maintenance': 'Website and system maintenance',
    'landing-page-development': 'Landing page development',
  },
}

export function localizePath(path: string, lang: Language) {
  const normalized = `/${path.replace(/^\/+|\/+$/g, '')}`
  if (lang === 'en') return normalized === '/' ? '/en/' : `/en${normalized}/`
  return normalized === '/' ? '/' : `${normalized}/`
}
